version: "3.9"

services:
  storage-service:
    build: .
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ollama

volumes:
  mongo-data:
